FROM xinjian1326/tdx-build-al3:latest

RUN cd /root && git clone https://github.com/jialez0/linux-sgx.git; \
cd /root/linux-sgx; \
make preparation; \
make sdk_install_pkg; \
echo yes | /root/linux-sgx/linux/installer/bin/sgx_linux_x64_sdk_*.bin; \
source /root/linux-sgx/sgxsdk/environment; \
make rpm_local_repo

RUN yum -y install yum-utils; \
yum-config-manager --add-repo file:////root/linux-sgx/linux/installer/rpm/sgx_rpm_local_repo; \
yum install -y --setopt=install_weak_deps=False --nogpgcheck libsgx-dcap-default-qpl

RUN cd /root/linux-sgx/external/dcap_source/QuoteGeneration/quote_wrapper/qgs; \
source /root/linux-sgx/sgxsdk/environment; \
make clean && make && cp qgs /usr/local/bin/

RUN rm -rf /etc/sgx_default_qcnl.conf; \
touch /etc/sgx_default_qcnl.conf; \
echo 'PCCS_URL=https://localhost:8081/sgx/certification/v4/\n\
USE_SECURE_CERT=FALSE' >> /etc/sgx_default_qcnl.conf
